language: general
sudo: required
sevices:
  - docker

before_install:
  - docker build -t ajaybojedla/hello-world-java .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajaybojedla/hello-world-java